//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO_list_automation_new.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IO_list_automation_new.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add before.
        /// </summary>
        internal static string AddBefore {
            get {
                return ResourceManager.GetString("AddBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button was pressed.
        /// </summary>
        internal static string ButtonPressed {
            get {
                return ResourceManager.GetString("ButtonPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height changed.
        /// </summary>
        internal static string ChangeHeight {
            get {
                return ResourceManager.GetString("ChangeHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width changed.
        /// </summary>
        internal static string ChangeWidth {
            get {
                return ResourceManager.GetString("ChangeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel column has number.
        /// </summary>
        internal static string ChannelHasNumber {
            get {
                return ResourceManager.GetString("ChannelHasNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel column is fully number.
        /// </summary>
        internal static string ChannelIsNumber {
            get {
                return ResourceManager.GetString("ChannelIsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column add drop down.
        /// </summary>
        internal static string ColumnAddDropDown {
            get {
                return ResourceManager.GetString("ColumnAddDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really whant to exit?.
        /// </summary>
        internal static string ConfirmExit {
            get {
                return ResourceManager.GetString("ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert list to data.
        /// </summary>
        internal static string ConvertListToData {
            get {
                return ResourceManager.GetString("ConvertListToData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to end.
        /// </summary>
        internal static string CopyEnd {
            get {
                return ResourceManager.GetString("CopyEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to end.
        /// </summary>
        internal static string CopyToEnd {
            get {
                return ResourceManager.GetString("CopyToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        internal static string CPU {
            get {
                return ResourceManager.GetString("CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        internal static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current debug level is set to.
        /// </summary>
        internal static string CurrentDebugLevel {
            get {
                return ResourceManager.GetString("CurrentDebugLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract data from excel file error, requested column is out of bound.
        /// </summary>
        internal static string DataReadFailBounds {
            get {
                return ResourceManager.GetString("DataReadFailBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract data from excel file error, this format of cell is not implemented.
        /// </summary>
        internal static string DataReadFailFormat {
            get {
                return ResourceManager.GetString("DataReadFailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database not found.
        /// </summary>
        internal static string DBNotFound {
            get {
                return ResourceManager.GetString("DBNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALARM.
        /// </summary>
        internal static string DebugAlarm {
            get {
                return ResourceManager.GetString("DebugAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRIT.
        /// </summary>
        internal static string DebugCritical {
            get {
                return ResourceManager.GetString("DebugCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug level.
        /// </summary>
        internal static string DebugLevel {
            get {
                return ResourceManager.GetString("DebugLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARN.
        /// </summary>
        internal static string DebugWarning {
            get {
                return ResourceManager.GetString("DebugWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Me.
        /// </summary>
        internal static string DeleteMe {
            get {
                return ResourceManager.GetString("DeleteMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing design file.
        /// </summary>
        internal static string DesignImport {
            get {
                return ResourceManager.GetString("DesignImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software is in early release, use with caution.
        /// </summary>
        internal static string EarlyReleaseWarning {
            get {
                return ResourceManager.GetString("EarlyReleaseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract data from design signals.
        /// </summary>
        internal static string ExtractDataFromDesign {
            get {
                return ResourceManager.GetString("ExtractDataFromDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic save file loading.
        /// </summary>
        internal static string FileAutoLoad {
            get {
                return ResourceManager.GetString("FileAutoLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File sellection canceled.
        /// </summary>
        internal static string FileSellectCanceled {
            get {
                return ResourceManager.GetString("FileSellectCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding funtion type in data.
        /// </summary>
        internal static string FindFunction {
            get {
                return ResourceManager.GetString("FindFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding object type in object.
        /// </summary>
        internal static string FindObjectType {
            get {
                return ResourceManager.GetString("FindObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function finished.
        /// </summary>
        internal static string FunctionFinished {
            get {
                return ResourceManager.GetString("FunctionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting data to grid.
        /// </summary>
        internal static string GetDataFromGrid {
            get {
                return ResourceManager.GetString("GetDataFromGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KKS from 4 parts are combined.
        /// </summary>
        internal static string KKSCombine {
            get {
                return ResourceManager.GetString("KKSCombine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data from file.
        /// </summary>
        internal static string LoadDataFromFile {
            get {
                return ResourceManager.GetString("LoadDataFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory area.
        /// </summary>
        internal static string MemoryArea {
            get {
                return ResourceManager.GetString("MemoryArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching unique Modules signals in Data.
        /// </summary>
        internal static string ModuleGenerateUniqueData {
            get {
                return ResourceManager.GetString("ModuleGenerateUniqueData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplier.
        /// </summary>
        internal static string Multiplier {
            get {
                return ResourceManager.GetString("Multiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no valid data in grid.
        /// </summary>
        internal static string NoDataGrid {
            get {
                return ResourceManager.GetString("NoDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        internal static string NoFile {
            get {
                return ResourceManager.GetString("NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function does not exist.
        /// </summary>
        internal static string NoFunction {
            get {
                return ResourceManager.GetString("NoFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to paste.
        /// </summary>
        internal static string NoPasteData {
            get {
                return ResourceManager.GetString("NoPasteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching unique KKS signals in Data.
        /// </summary>
        internal static string ObjectGenerateUniqueData {
            get {
                return ResourceManager.GetString("ObjectGenerateUniqueData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer object data to data signals .
        /// </summary>
        internal static string ObjectTransferToData {
            get {
                return ResourceManager.GetString("ObjectTransferToData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        internal static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter not found when parsing.
        /// </summary>
        internal static string ParameterNotFound {
            get {
                return ResourceManager.GetString("ParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste at.
        /// </summary>
        internal static string PasteAt {
            get {
                return ResourceManager.GetString("PasteAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste data.
        /// </summary>
        internal static string PasteData {
            get {
                return ResourceManager.GetString("PasteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin column has number.
        /// </summary>
        internal static string PinHasNumber {
            get {
                return ResourceManager.GetString("PinHasNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin column is fully number.
        /// </summary>
        internal static string PinIsNumber {
            get {
                return ResourceManager.GetString("PinIsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress bar value is out of range.
        /// </summary>
        internal static string ProgressBarOutRange {
            get {
                return ResourceManager.GetString("ProgressBarOutRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Putting data to grid.
        /// </summary>
        internal static string PutDataToGrid {
            get {
                return ResourceManager.GetString("PutDataToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row offset.
        /// </summary>
        internal static string RowOffset {
            get {
                return ResourceManager.GetString("RowOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving data to file.
        /// </summary>
        internal static string SaveDataToFile {
            get {
                return ResourceManager.GetString("SaveDataToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCADA.
        /// </summary>
        internal static string SCADA {
            get {
                return ResourceManager.GetString("SCADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software is started, version is.
        /// </summary>
        internal static string SoftwareStart {
            get {
                return ResourceManager.GetString("SoftwareStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement.
        /// </summary>
        internal static string Statement {
            get {
                return ResourceManager.GetString("Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To much data to paste.
        /// </summary>
        internal static string ToMuchDataPaste {
            get {
                return ResourceManager.GetString("ToMuchDataPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        internal static string Variables {
            get {
                return ResourceManager.GetString("Variables", resourceCulture);
            }
        }
    }
}
