//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO_list_automation_new.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesColumns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesColumns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IO_list_automation_new.Properties.ResourcesColumns", typeof(ResourcesColumns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column add drop down.
        /// </summary>
        internal static string AddDropDown {
            get {
                return ResourceManager.GetString("AddDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet.
        /// </summary>
        internal static string Cabinet {
            get {
                return ResourceManager.GetString("Cabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable.
        /// </summary>
        internal static string Cable {
            get {
                return ResourceManager.GetString("Cable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        internal static string Changed {
            get {
                return ResourceManager.GetString("Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string ChoiceData {
            get {
                return ResourceManager.GetString("ChoiceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF.
        /// </summary>
        internal static string ChoiceIf {
            get {
                return ResourceManager.GetString("ChoiceIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string ChoiceIndex {
            get {
                return ResourceManager.GetString("ChoiceIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO.
        /// </summary>
        internal static string ChoiceIO {
            get {
                return ResourceManager.GetString("ChoiceIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is empty.
        /// </summary>
        internal static string ChoiceIsEmpty {
            get {
                return ResourceManager.GetString("ChoiceIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not empty.
        /// </summary>
        internal static string ChoiceIsNotEmpty {
            get {
                return ResourceManager.GetString("ChoiceIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string ChoiceObject {
            get {
                return ResourceManager.GetString("ChoiceObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAB.
        /// </summary>
        internal static string ChoiceTab {
            get {
                return ResourceManager.GetString("ChoiceTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag type.
        /// </summary>
        internal static string ChoiceTagType {
            get {
                return ResourceManager.GetString("ChoiceTagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string ChoiceText {
            get {
                return ResourceManager.GetString("ChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        internal static string CPU {
            get {
                return ResourceManager.GetString("CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device type text.
        /// </summary>
        internal static string DeviceTypeText {
            get {
                return ResourceManager.GetString("DeviceTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False Text.
        /// </summary>
        internal static string FalseText {
            get {
                return ResourceManager.GetString("FalseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string Function1 {
            get {
                return ResourceManager.GetString("Function1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string Function2 {
            get {
                return ResourceManager.GetString("Function2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Text.
        /// </summary>
        internal static string FunctionText {
            get {
                return ResourceManager.GetString("FunctionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function text with 1 part.
        /// </summary>
        internal static string FunctionText1 {
            get {
                return ResourceManager.GetString("FunctionText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function text with 2 part 1/2.
        /// </summary>
        internal static string FunctionText1o2 {
            get {
                return ResourceManager.GetString("FunctionText1o2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function text with 2 part 2/2.
        /// </summary>
        internal static string FunctionText2o2 {
            get {
                return ResourceManager.GetString("FunctionText2o2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Text.
        /// </summary>
        internal static string IOText {
            get {
                return ResourceManager.GetString("IOText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KKS.
        /// </summary>
        internal static string KKS {
            get {
                return ResourceManager.GetString("KKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KKS Device.
        /// </summary>
        internal static string KKSDevice {
            get {
                return ResourceManager.GetString("KKSDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KKS Function.
        /// </summary>
        internal static string KKSFunction {
            get {
                return ResourceManager.GetString("KKSFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KKS Location.
        /// </summary>
        internal static string KKSLocation {
            get {
                return ResourceManager.GetString("KKSLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KKS Plant.
        /// </summary>
        internal static string KKSPlant {
            get {
                return ResourceManager.GetString("KKSPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        internal static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Type.
        /// </summary>
        internal static string ModuleType {
            get {
                return ResourceManager.GetString("ModuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Name.
        /// </summary>
        internal static string ObjectName {
            get {
                return ResourceManager.GetString("ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Specifics.
        /// </summary>
        internal static string ObjectSpecifics {
            get {
                return ResourceManager.GetString("ObjectSpecifics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Type.
        /// </summary>
        internal static string ObjectType {
            get {
                return ResourceManager.GetString("ObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operative.
        /// </summary>
        internal static string Operative {
            get {
                return ResourceManager.GetString("Operative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        internal static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Max.
        /// </summary>
        internal static string RangeMax {
            get {
                return ResourceManager.GetString("RangeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Min.
        /// </summary>
        internal static string RangeMin {
            get {
                return ResourceManager.GetString("RangeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        internal static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name.
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal.
        /// </summary>
        internal static string Terminal {
            get {
                return ResourceManager.GetString("Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True Text.
        /// </summary>
        internal static string TrueText {
            get {
                return ResourceManager.GetString("TrueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        internal static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
    }
}
