//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO_list_automation_new.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IO_list_automation_new.Properties.ResourcesUI", typeof(ResourcesUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare with new design.
        /// </summary>
        internal static string CompareWithNewDesign {
            get {
                return ResourceManager.GetString("CompareWithNewDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare.
        /// </summary>
        internal static string Declare {
            get {
                return ResourceManager.GetString("Declare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare DB edit.
        /// </summary>
        internal static string DeclareDBEdit {
            get {
                return ResourceManager.GetString("DeclareDBEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate declarations.
        /// </summary>
        internal static string DeclareGenerate {
            get {
                return ResourceManager.GetString("DeclareGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find function.
        /// </summary>
        internal static string FindFunction {
            get {
                return ResourceManager.GetString("FindFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find unique modules.
        /// </summary>
        internal static string FindUniqueModules {
            get {
                return ResourceManager.GetString("FindUniqueModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get data from design.
        /// </summary>
        internal static string GetDataFromDesign {
            get {
                return ResourceManager.GetString("GetDataFromDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance.
        /// </summary>
        internal static string Instance {
            get {
                return ResourceManager.GetString("Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance DB edit.
        /// </summary>
        internal static string InstanceDBEdit {
            get {
                return ResourceManager.GetString("InstanceDBEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate instances.
        /// </summary>
        internal static string InstanceGenerate {
            get {
                return ResourceManager.GetString("InstanceGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO.
        /// </summary>
        internal static string IO {
            get {
                return ResourceManager.GetString("IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO DB edit.
        /// </summary>
        internal static string IODBEdit {
            get {
                return ResourceManager.GetString("IODBEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO generate.
        /// </summary>
        internal static string IOGenerate {
            get {
                return ResourceManager.GetString("IOGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KKS combine.
        /// </summary>
        internal static string KKSCombine {
            get {
                return ResourceManager.GetString("KKSCombine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadAll.
        /// </summary>
        internal static string LoadAll {
            get {
                return ResourceManager.GetString("LoadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lietuviu.
        /// </summary>
        internal static string LT {
            get {
                return ResourceManager.GetString("LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        internal static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find object types.
        /// </summary>
        internal static string ObjectFindType {
            get {
                return ResourceManager.GetString("ObjectFindType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        internal static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects DB edit.
        /// </summary>
        internal static string ObjectsEdit {
            get {
                return ResourceManager.GetString("ObjectsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find unique objects.
        /// </summary>
        internal static string ObjectsFindUnique {
            get {
                return ResourceManager.GetString("ObjectsFindUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer data from objects to data.
        /// </summary>
        internal static string ObjectsTransferData {
            get {
                return ResourceManager.GetString("ObjectsTransferData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveAll.
        /// </summary>
        internal static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCADA DB edit.
        /// </summary>
        internal static string ScadaEdit {
            get {
                return ResourceManager.GetString("ScadaEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCADA generate Instances.
        /// </summary>
        internal static string SCADAGenerate {
            get {
                return ResourceManager.GetString("SCADAGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer project to data.
        /// </summary>
        internal static string TransferProjectToData {
            get {
                return ResourceManager.GetString("TransferProjectToData", resourceCulture);
            }
        }
    }
}
