//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO_list_automation_new.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class SettingsData : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsData defaultInstance = ((SettingsData)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsData())));
        
        public static SettingsData Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KKSEditText01 {
            get {
                return ((string)(this["KKSEditText01"]));
            }
            set {
                this["KKSEditText01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KKSEditText12 {
            get {
                return ((string)(this["KKSEditText12"]));
            }
            set {
                this["KKSEditText12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KKSEditText23 {
            get {
                return ((string)(this["KKSEditText23"]));
            }
            set {
                this["KKSEditText23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KKSEditText34 {
            get {
                return ((string)(this["KKSEditText34"]));
            }
            set {
                this["KKSEditText34"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KKSEditText45 {
            get {
                return ((string)(this["KKSEditText45"]));
            }
            set {
                this["KKSEditText45"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KKSEditCheckPart1 {
            get {
                return ((bool)(this["KKSEditCheckPart1"]));
            }
            set {
                this["KKSEditCheckPart1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KKSEditCheckPart2 {
            get {
                return ((bool)(this["KKSEditCheckPart2"]));
            }
            set {
                this["KKSEditCheckPart2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KKSEditCheckPart3 {
            get {
                return ((bool)(this["KKSEditCheckPart3"]));
            }
            set {
                this["KKSEditCheckPart3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KKSEditCheckPart4 {
            get {
                return ((bool)(this["KKSEditCheckPart4"]));
            }
            set {
                this["KKSEditCheckPart4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public string ObjectSpecificsSeparator {
            get {
                return ((string)(this["ObjectSpecificsSeparator"]));
            }
            set {
                this["ObjectSpecificsSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(":")]
        public string FunctionTextSeparator {
            get {
                return ((string)(this["FunctionTextSeparator"]));
            }
            set {
                this["FunctionTextSeparator"] = value;
            }
        }
    }
}
