//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO_list_automation_new.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class SettingsDesignInput : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsDesignInput defaultInstance = ((SettingsDesignInput)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsDesignInput())));
        
        public static SettingsDesignInput Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int RowOffset {
            get {
                return ((int)(this["RowOffset"]));
            }
            set {
                this["RowOffset"] = value;
            }
        }
    }
}
