//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO_list_automation_new.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class SettingsDesign : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsDesign defaultInstance = ((SettingsDesign)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsDesign())));
        
        public static SettingsDesign Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ColumnID {
            get {
                return ((int)(this["ColumnID"]));
            }
            set {
                this["ColumnID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ColumnCPU {
            get {
                return ((int)(this["ColumnCPU"]));
            }
            set {
                this["ColumnCPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ColumnKKS {
            get {
                return ((int)(this["ColumnKKS"]));
            }
            set {
                this["ColumnKKS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int ColumnRangeMin {
            get {
                return ((int)(this["ColumnRangeMin"]));
            }
            set {
                this["ColumnRangeMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ColumnRangeMax {
            get {
                return ((int)(this["ColumnRangeMax"]));
            }
            set {
                this["ColumnRangeMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int ColumnUnits {
            get {
                return ((int)(this["ColumnUnits"]));
            }
            set {
                this["ColumnUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int ColumnFalseText {
            get {
                return ((int)(this["ColumnFalseText"]));
            }
            set {
                this["ColumnFalseText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int ColumnTrueText {
            get {
                return ((int)(this["ColumnTrueText"]));
            }
            set {
                this["ColumnTrueText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int ColumnRevision {
            get {
                return ((int)(this["ColumnRevision"]));
            }
            set {
                this["ColumnRevision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int ColumnCable {
            get {
                return ((int)(this["ColumnCable"]));
            }
            set {
                this["ColumnCable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ColumnCabinet {
            get {
                return ((int)(this["ColumnCabinet"]));
            }
            set {
                this["ColumnCabinet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ColumnModuleName {
            get {
                return ((int)(this["ColumnModuleName"]));
            }
            set {
                this["ColumnModuleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ColumnPin {
            get {
                return ((int)(this["ColumnPin"]));
            }
            set {
                this["ColumnPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int ColumnChannel {
            get {
                return ((int)(this["ColumnChannel"]));
            }
            set {
                this["ColumnChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int ColumnIOText {
            get {
                return ((int)(this["ColumnIOText"]));
            }
            set {
                this["ColumnIOText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int ColumnPage {
            get {
                return ((int)(this["ColumnPage"]));
            }
            set {
                this["ColumnPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int ColumnChanged {
            get {
                return ((int)(this["ColumnChanged"]));
            }
            set {
                this["ColumnChanged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public int ColumnTerminal {
            get {
                return ((int)(this["ColumnTerminal"]));
            }
            set {
                this["ColumnTerminal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int ColumnTag {
            get {
                return ((int)(this["ColumnTag"]));
            }
            set {
                this["ColumnTag"] = value;
            }
        }
    }
}
