//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO_list_automation_new.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1680")]
        public uint AplicationHeight {
            get {
                return ((uint)(this["AplicationHeight"]));
            }
            set {
                this["AplicationHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1080")]
        public uint AplicationWidth {
            get {
                return ((uint)(this["AplicationWidth"]));
            }
            set {
                this["AplicationWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint DebugLevel {
            get {
                return ((uint)(this["DebugLevel"]));
            }
            set {
                this["DebugLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EN")]
        public string IOLanguage {
            get {
                return ((string)(this["IOLanguage"]));
            }
            set {
                this["IOLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EN")]
        public string ApplicationLanguage {
            get {
                return ((string)(this["ApplicationLanguage"]));
            }
            set {
                this["ApplicationLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Siemens")]
        public string SelectedCPU {
            get {
                return ((string)(this["SelectedCPU"]));
            }
            set {
                this["SelectedCPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WinCC")]
        public string SelectedSCADA {
            get {
                return ((string)(this["SelectedSCADA"]));
            }
            set {
                this["SelectedSCADA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutomaticColumnWidth {
            get {
                return ((bool)(this["AutomaticColumnWidth"]));
            }
            set {
                this["AutomaticColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DeleteRowIfNoModule {
            get {
                return ((bool)(this["DeleteRowIfNoModule"]));
            }
            set {
                this["DeleteRowIfNoModule"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ExcelColumnCPU {
            get {
                return ((int)(this["ExcelColumnCPU"]));
            }
            set {
                this["ExcelColumnCPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ExcelColumnKKS {
            get {
                return ((int)(this["ExcelColumnKKS"]));
            }
            set {
                this["ExcelColumnKKS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ExcelColumnRangeMin {
            get {
                return ((int)(this["ExcelColumnRangeMin"]));
            }
            set {
                this["ExcelColumnRangeMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ExcelColumnRangeMax {
            get {
                return ((int)(this["ExcelColumnRangeMax"]));
            }
            set {
                this["ExcelColumnRangeMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ExcelColumnUnits {
            get {
                return ((int)(this["ExcelColumnUnits"]));
            }
            set {
                this["ExcelColumnUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ExcelColumnFalseText {
            get {
                return ((int)(this["ExcelColumnFalseText"]));
            }
            set {
                this["ExcelColumnFalseText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ExcelColumnTrueText {
            get {
                return ((int)(this["ExcelColumnTrueText"]));
            }
            set {
                this["ExcelColumnTrueText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ExcelColumnRevision {
            get {
                return ((int)(this["ExcelColumnRevision"]));
            }
            set {
                this["ExcelColumnRevision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ExcelColumnCable {
            get {
                return ((int)(this["ExcelColumnCable"]));
            }
            set {
                this["ExcelColumnCable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ExcelColumnCabinet {
            get {
                return ((int)(this["ExcelColumnCabinet"]));
            }
            set {
                this["ExcelColumnCabinet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ExcelColumnModuleName {
            get {
                return ((int)(this["ExcelColumnModuleName"]));
            }
            set {
                this["ExcelColumnModuleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ExcelColumnPin {
            get {
                return ((int)(this["ExcelColumnPin"]));
            }
            set {
                this["ExcelColumnPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ExcelColumnChannel {
            get {
                return ((int)(this["ExcelColumnChannel"]));
            }
            set {
                this["ExcelColumnChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ExcelColumnIOText {
            get {
                return ((int)(this["ExcelColumnIOText"]));
            }
            set {
                this["ExcelColumnIOText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ExcelColumnPage {
            get {
                return ((int)(this["ExcelColumnPage"]));
            }
            set {
                this["ExcelColumnPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DesignColumnID {
            get {
                return ((int)(this["DesignColumnID"]));
            }
            set {
                this["DesignColumnID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DesignColumnCPU {
            get {
                return ((int)(this["DesignColumnCPU"]));
            }
            set {
                this["DesignColumnCPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int DesignColumnKKS {
            get {
                return ((int)(this["DesignColumnKKS"]));
            }
            set {
                this["DesignColumnKKS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int DesignColumnRangeMin {
            get {
                return ((int)(this["DesignColumnRangeMin"]));
            }
            set {
                this["DesignColumnRangeMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DesignColumnRangeMax {
            get {
                return ((int)(this["DesignColumnRangeMax"]));
            }
            set {
                this["DesignColumnRangeMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int DesignColumnUnits {
            get {
                return ((int)(this["DesignColumnUnits"]));
            }
            set {
                this["DesignColumnUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int DesignColumnFalseText {
            get {
                return ((int)(this["DesignColumnFalseText"]));
            }
            set {
                this["DesignColumnFalseText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int DesignColumnTrueText {
            get {
                return ((int)(this["DesignColumnTrueText"]));
            }
            set {
                this["DesignColumnTrueText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int DesignColumnRevision {
            get {
                return ((int)(this["DesignColumnRevision"]));
            }
            set {
                this["DesignColumnRevision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int DesignColumnCable {
            get {
                return ((int)(this["DesignColumnCable"]));
            }
            set {
                this["DesignColumnCable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DesignColumnCabinet {
            get {
                return ((int)(this["DesignColumnCabinet"]));
            }
            set {
                this["DesignColumnCabinet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int DesignColumnModuleName {
            get {
                return ((int)(this["DesignColumnModuleName"]));
            }
            set {
                this["DesignColumnModuleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int DesignColumnPin {
            get {
                return ((int)(this["DesignColumnPin"]));
            }
            set {
                this["DesignColumnPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int DesignColumnChannel {
            get {
                return ((int)(this["DesignColumnChannel"]));
            }
            set {
                this["DesignColumnChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int DesignColumnIOText {
            get {
                return ((int)(this["DesignColumnIOText"]));
            }
            set {
                this["DesignColumnIOText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int DesignColumnPage {
            get {
                return ((int)(this["DesignColumnPage"]));
            }
            set {
                this["DesignColumnPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int DesignColumnChanged {
            get {
                return ((int)(this["DesignColumnChanged"]));
            }
            set {
                this["DesignColumnChanged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ExcelColumnChanged {
            get {
                return ((int)(this["ExcelColumnChanged"]));
            }
            set {
                this["ExcelColumnChanged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ExcelColumnID {
            get {
                return ((int)(this["ExcelColumnID"]));
            }
            set {
                this["ExcelColumnID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InputDataPinIsNumber {
            get {
                return ((bool)(this["InputDataPinIsNumber"]));
            }
            set {
                this["InputDataPinIsNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InputDataChannelIsNumber {
            get {
                return ((bool)(this["InputDataChannelIsNumber"]));
            }
            set {
                this["InputDataChannelIsNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InputDataPinHasNumber {
            get {
                return ((bool)(this["InputDataPinHasNumber"]));
            }
            set {
                this["InputDataPinHasNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InputDataChannelHasNumber {
            get {
                return ((bool)(this["InputDataChannelHasNumber"]));
            }
            set {
                this["InputDataChannelHasNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ExcelRowOffset {
            get {
                return ((int)(this["ExcelRowOffset"]));
            }
            set {
                this["ExcelRowOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DataColumnID {
            get {
                return ((int)(this["DataColumnID"]));
            }
            set {
                this["DataColumnID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DataColumnCPU {
            get {
                return ((int)(this["DataColumnCPU"]));
            }
            set {
                this["DataColumnCPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DataColumnKKS {
            get {
                return ((int)(this["DataColumnKKS"]));
            }
            set {
                this["DataColumnKKS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int DataColumnRangeMin {
            get {
                return ((int)(this["DataColumnRangeMin"]));
            }
            set {
                this["DataColumnRangeMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int DataColumnRangeMax {
            get {
                return ((int)(this["DataColumnRangeMax"]));
            }
            set {
                this["DataColumnRangeMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public int DataColumnUnits {
            get {
                return ((int)(this["DataColumnUnits"]));
            }
            set {
                this["DataColumnUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public int DataColumnFalseText {
            get {
                return ((int)(this["DataColumnFalseText"]));
            }
            set {
                this["DataColumnFalseText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int DataColumnTrueText {
            get {
                return ((int)(this["DataColumnTrueText"]));
            }
            set {
                this["DataColumnTrueText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26")]
        public int DataColumnRevision {
            get {
                return ((int)(this["DataColumnRevision"]));
            }
            set {
                this["DataColumnRevision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int DataColumnCable {
            get {
                return ((int)(this["DataColumnCable"]));
            }
            set {
                this["DataColumnCable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int DataColumnCabinet {
            get {
                return ((int)(this["DataColumnCabinet"]));
            }
            set {
                this["DataColumnCabinet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int DataColumnModuleName {
            get {
                return ((int)(this["DataColumnModuleName"]));
            }
            set {
                this["DataColumnModuleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int DataColumnPin {
            get {
                return ((int)(this["DataColumnPin"]));
            }
            set {
                this["DataColumnPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public int DataColumnChannel {
            get {
                return ((int)(this["DataColumnChannel"]));
            }
            set {
                this["DataColumnChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int DataColumnIOText {
            get {
                return ((int)(this["DataColumnIOText"]));
            }
            set {
                this["DataColumnIOText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int DataColumnPage {
            get {
                return ((int)(this["DataColumnPage"]));
            }
            set {
                this["DataColumnPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public int DataColumnChanged {
            get {
                return ((int)(this["DataColumnChanged"]));
            }
            set {
                this["DataColumnChanged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int DataColumnOperative {
            get {
                return ((int)(this["DataColumnOperative"]));
            }
            set {
                this["DataColumnOperative"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int DataColumnKKSPlant {
            get {
                return ((int)(this["DataColumnKKSPlant"]));
            }
            set {
                this["DataColumnKKSPlant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int DataColumnKKSLocation {
            get {
                return ((int)(this["DataColumnKKSLocation"]));
            }
            set {
                this["DataColumnKKSLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int DataColumnKKSDevice {
            get {
                return ((int)(this["DataColumnKKSDevice"]));
            }
            set {
                this["DataColumnKKSDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int DataColumnKKSFunction {
            get {
                return ((int)(this["DataColumnKKSFunction"]));
            }
            set {
                this["DataColumnKKSFunction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int DataColumnUsed {
            get {
                return ((int)(this["DataColumnUsed"]));
            }
            set {
                this["DataColumnUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int DataColumnObjectType {
            get {
                return ((int)(this["DataColumnObjectType"]));
            }
            set {
                this["DataColumnObjectType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DataColumnObjectName {
            get {
                return ((int)(this["DataColumnObjectName"]));
            }
            set {
                this["DataColumnObjectName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int DataColumnObjectDetalisation {
            get {
                return ((int)(this["DataColumnObjectDetalisation"]));
            }
            set {
                this["DataColumnObjectDetalisation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int DataColumnFunctionText {
            get {
                return ((int)(this["DataColumnFunctionText"]));
            }
            set {
                this["DataColumnFunctionText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int DataColumnFunction {
            get {
                return ((int)(this["DataColumnFunction"]));
            }
            set {
                this["DataColumnFunction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ObjectsColumnID {
            get {
                return ((int)(this["ObjectsColumnID"]));
            }
            set {
                this["ObjectsColumnID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ObjectsColumnCPU {
            get {
                return ((int)(this["ObjectsColumnCPU"]));
            }
            set {
                this["ObjectsColumnCPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ObjectsColumnKKS {
            get {
                return ((int)(this["ObjectsColumnKKS"]));
            }
            set {
                this["ObjectsColumnKKS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ObjectsColumnOperative {
            get {
                return ((int)(this["ObjectsColumnOperative"]));
            }
            set {
                this["ObjectsColumnOperative"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ObjectsColumnObjectType {
            get {
                return ((int)(this["ObjectsColumnObjectType"]));
            }
            set {
                this["ObjectsColumnObjectType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ObjectsColumnObjectName {
            get {
                return ((int)(this["ObjectsColumnObjectName"]));
            }
            set {
                this["ObjectsColumnObjectName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int DataColumnTerminal {
            get {
                return ((int)(this["DataColumnTerminal"]));
            }
            set {
                this["DataColumnTerminal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public int DesignColumnTerminal {
            get {
                return ((int)(this["DesignColumnTerminal"]));
            }
            set {
                this["DesignColumnTerminal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ExcelColumnTerminal {
            get {
                return ((int)(this["ExcelColumnTerminal"]));
            }
            set {
                this["ExcelColumnTerminal"] = value;
            }
        }
    }
}
