//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO_list_automation_new.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class SettingsData : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsData defaultInstance = ((SettingsData)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsData())));
        
        public static SettingsData Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ColumnID {
            get {
                return ((int)(this["ColumnID"]));
            }
            set {
                this["ColumnID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ColumnCPU {
            get {
                return ((int)(this["ColumnCPU"]));
            }
            set {
                this["ColumnCPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ColumnKKS {
            get {
                return ((int)(this["ColumnKKS"]));
            }
            set {
                this["ColumnKKS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int ColumnRangeMin {
            get {
                return ((int)(this["ColumnRangeMin"]));
            }
            set {
                this["ColumnRangeMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int ColumnRangeMax {
            get {
                return ((int)(this["ColumnRangeMax"]));
            }
            set {
                this["ColumnRangeMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public int ColumnUnits {
            get {
                return ((int)(this["ColumnUnits"]));
            }
            set {
                this["ColumnUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public int ColumnFalseText {
            get {
                return ((int)(this["ColumnFalseText"]));
            }
            set {
                this["ColumnFalseText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int ColumnTrueText {
            get {
                return ((int)(this["ColumnTrueText"]));
            }
            set {
                this["ColumnTrueText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26")]
        public int ColumnRevision {
            get {
                return ((int)(this["ColumnRevision"]));
            }
            set {
                this["ColumnRevision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int ColumnCable {
            get {
                return ((int)(this["ColumnCable"]));
            }
            set {
                this["ColumnCable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ColumnCabinet {
            get {
                return ((int)(this["ColumnCabinet"]));
            }
            set {
                this["ColumnCabinet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int ColumnModuleName {
            get {
                return ((int)(this["ColumnModuleName"]));
            }
            set {
                this["ColumnModuleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int ColumnPin {
            get {
                return ((int)(this["ColumnPin"]));
            }
            set {
                this["ColumnPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public int ColumnChannel {
            get {
                return ((int)(this["ColumnChannel"]));
            }
            set {
                this["ColumnChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int ColumnIOText {
            get {
                return ((int)(this["ColumnIOText"]));
            }
            set {
                this["ColumnIOText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int ColumnPage {
            get {
                return ((int)(this["ColumnPage"]));
            }
            set {
                this["ColumnPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public int ColumnChanged {
            get {
                return ((int)(this["ColumnChanged"]));
            }
            set {
                this["ColumnChanged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ColumnOperative {
            get {
                return ((int)(this["ColumnOperative"]));
            }
            set {
                this["ColumnOperative"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ColumnKKSPlant {
            get {
                return ((int)(this["ColumnKKSPlant"]));
            }
            set {
                this["ColumnKKSPlant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ColumnKKSLocation {
            get {
                return ((int)(this["ColumnKKSLocation"]));
            }
            set {
                this["ColumnKKSLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int ColumnKKSDevice {
            get {
                return ((int)(this["ColumnKKSDevice"]));
            }
            set {
                this["ColumnKKSDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int ColumnKKSFunction {
            get {
                return ((int)(this["ColumnKKSFunction"]));
            }
            set {
                this["ColumnKKSFunction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int ColumnUsed {
            get {
                return ((int)(this["ColumnUsed"]));
            }
            set {
                this["ColumnUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int ColumnObjectType {
            get {
                return ((int)(this["ColumnObjectType"]));
            }
            set {
                this["ColumnObjectType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ColumnObjectName {
            get {
                return ((int)(this["ColumnObjectName"]));
            }
            set {
                this["ColumnObjectName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int ColumnObjectSpecifics {
            get {
                return ((int)(this["ColumnObjectSpecifics"]));
            }
            set {
                this["ColumnObjectSpecifics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int ColumnFunctionText {
            get {
                return ((int)(this["ColumnFunctionText"]));
            }
            set {
                this["ColumnFunctionText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int ColumnFunction {
            get {
                return ((int)(this["ColumnFunction"]));
            }
            set {
                this["ColumnFunction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int ColumnTerminal {
            get {
                return ((int)(this["ColumnTerminal"]));
            }
            set {
                this["ColumnTerminal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KKSEditText01 {
            get {
                return ((string)(this["KKSEditText01"]));
            }
            set {
                this["KKSEditText01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KKSEditText12 {
            get {
                return ((string)(this["KKSEditText12"]));
            }
            set {
                this["KKSEditText12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KKSEditText23 {
            get {
                return ((string)(this["KKSEditText23"]));
            }
            set {
                this["KKSEditText23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KKSEditText34 {
            get {
                return ((string)(this["KKSEditText34"]));
            }
            set {
                this["KKSEditText34"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KKSEditText45 {
            get {
                return ((string)(this["KKSEditText45"]));
            }
            set {
                this["KKSEditText45"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KKSEditCheckPart1 {
            get {
                return ((bool)(this["KKSEditCheckPart1"]));
            }
            set {
                this["KKSEditCheckPart1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KKSEditCheckPart2 {
            get {
                return ((bool)(this["KKSEditCheckPart2"]));
            }
            set {
                this["KKSEditCheckPart2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KKSEditCheckPart3 {
            get {
                return ((bool)(this["KKSEditCheckPart3"]));
            }
            set {
                this["KKSEditCheckPart3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KKSEditCheckPart4 {
            get {
                return ((bool)(this["KKSEditCheckPart4"]));
            }
            set {
                this["KKSEditCheckPart4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28")]
        public int ColumnTag {
            get {
                return ((int)(this["ColumnTag"]));
            }
            set {
                this["ColumnTag"] = value;
            }
        }
    }
}
