//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO_list_automation_new.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class SettingsObject : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsObject defaultInstance = ((SettingsObject)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsObject())));
        
        public static SettingsObject Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ColumnID {
            get {
                return ((int)(this["ColumnID"]));
            }
            set {
                this["ColumnID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ColumnCPU {
            get {
                return ((int)(this["ColumnCPU"]));
            }
            set {
                this["ColumnCPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ColumnKKS {
            get {
                return ((int)(this["ColumnKKS"]));
            }
            set {
                this["ColumnKKS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ColumnOperative {
            get {
                return ((int)(this["ColumnOperative"]));
            }
            set {
                this["ColumnOperative"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ColumnObjectType {
            get {
                return ((int)(this["ColumnObjectType"]));
            }
            set {
                this["ColumnObjectType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ColumnObjectName {
            get {
                return ((int)(this["ColumnObjectName"]));
            }
            set {
                this["ColumnObjectName"] = value;
            }
        }
    }
}
