//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO_list_automation_new.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class SettingsObject : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsObject defaultInstance = ((SettingsObject)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsObject())));
        
        public static SettingsObject Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ObjectsColumnID {
            get {
                return ((int)(this["ObjectsColumnID"]));
            }
            set {
                this["ObjectsColumnID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ObjectsColumnCPU {
            get {
                return ((int)(this["ObjectsColumnCPU"]));
            }
            set {
                this["ObjectsColumnCPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ObjectsColumnKKS {
            get {
                return ((int)(this["ObjectsColumnKKS"]));
            }
            set {
                this["ObjectsColumnKKS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ObjectsColumnOperative {
            get {
                return ((int)(this["ObjectsColumnOperative"]));
            }
            set {
                this["ObjectsColumnOperative"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ObjectsColumnObjectType {
            get {
                return ((int)(this["ObjectsColumnObjectType"]));
            }
            set {
                this["ObjectsColumnObjectType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ObjectsColumnObjectName {
            get {
                return ((int)(this["ObjectsColumnObjectName"]));
            }
            set {
                this["ObjectsColumnObjectName"] = value;
            }
        }
    }
}
